apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: view
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edit
rules:
  - apiGroups: [""]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: view-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    namespace: api
    name: webdev@OTAPRD1312ops.onmicrosoft.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    namespace: web
    name: apidev@OTAPRD1312ops.onmicrosoft.com
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: edit-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    namespace: api
    name: apidev@OTAPRD1312ops.onmicrosoft.com
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    namespace: web
    name: webdev@OTAPRD1312ops.onmicrosoft.com
